version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        depends_on:
            - php
            - mysql
        networks:
            - app-network

    php:
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

    mysql:
          image: mysql:latest
          restart: always
          ports:
              - 3306:3306
          environment:
              MYSQL_DATABASE: lumen
              MYSQL_USER: gustavo
              MYSQL_PASSWORD: cabecinhabranca
              MYSQL_ROOT_PASSWORD: cabecinhabranca
          networks:
            - app-network

networks:
    app-network:
        driver: bridge